/* Load this script using conditional IE comments if you need to support IE 7 and IE 6. */

window.onload = function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'CharlieGordon\'">' + entity + '</span>' + html;
	}
	var icons = {
			'icon-cabinet' : '&#xe004;',
			'icon-microphone' : '&#xe005;',
			'icon-checkmark' : '&#xe006;',
			'icon-cancel' : '&#xe007;',
			'icon-print' : '&#xe008;',
			'icon-megaphone' : '&#xe00a;',
			'icon-paper-plane' : '&#xe001;',
			'icon-thumbs-up' : '&#xe000;',
			'icon-thumbs-down' : '&#xe010;',
			'icon-user-add' : '&#xe011;',
			'icon-user' : '&#xe012;',
			'icon-users' : '&#xe013;',
			'icon-users-2' : '&#xe017;',
			'icon-chevron-left' : '&#xf053;',
			'icon-chevron-right' : '&#xf054;',
			'icon-plus' : '&#xf067;',
			'icon-minus' : '&#xf068;',
			'icon-folder-open' : '&#xe018;',
			'icon-repeat' : '&#xe019;',
			'icon-spinner' : '&#xe01a;',
			'icon-zoom-in' : '&#xe01b;',
			'icon-zoom-out' : '&#xe01d;',
			'icon-search' : '&#xe01c;',
			'icon-reorder' : '&#xf0c9;',
			'icon-quote' : '&#xe01e;',
			'icon-quote-2' : '&#xe029;',
			'icon-link' : '&#xe02d;',
			'icon-quotes-left' : '&#xe02e;',
			'icon-comments' : '&#xe02f;',
			'icon-comments-alt' : '&#xe037;',
			'icon-chat' : '&#xe038;',
			'icon-download' : '&#xf02b;',
			'icon-pencil' : '&#xe03d;',
			'icon-pencil-2' : '&#xe03f;',
			'icon-pictures' : '&#xe03e;',
			'icon-picture' : '&#xe040;',
			'icon-phone' : '&#xe043;',
			'icon-mobile' : '&#xf10b;',
			'icon-star' : '&#xe041;',
			'icon-star-2' : '&#xe042;',
			'icon-star-3' : '&#xe044;',
			'icon-heart-empty' : '&#xe045;',
			'icon-heart' : '&#xf074;',
			'icon-location' : '&#xf02f;',
			'icon-map' : '&#xf01e;',
			'icon-warning' : '&#xe046;',
			'icon-clock' : '&#xe047;',
			'icon-code' : '&#xe049;',
			'icon-braces' : '&#xf015;',
			'icon-paperclip' : '&#xe04a;',
			'icon-calendar' : '&#xe04b;',
			'icon-calendar-2' : '&#xe04d;',
			'icon-tag' : '&#xf08a;',
			'icon-tags' : '&#xf004;',
			'icon-record' : '&#xf013;',
			'icon-random' : '&#xe04e;',
			'icon-sound' : '&#xe04f;',
			'icon-film' : '&#xe051;',
			'icon-circleinfo' : '&#xe016;',
			'icon-info' : '&#xe053;',
			'icon-help' : '&#xe057;',
			'icon-asterisk' : '&#xe058;',
			'icon-file' : '&#xe059;',
			'icon-vote' : '&#xe009;',
			'icon-vote-2' : '&#xe00c;',
			'icon-angle-left' : '&#xf104;',
			'icon-angle-right' : '&#xf105;',
			'icon-angle-up' : '&#xf106;',
			'icon-angle-down' : '&#xf107;',
			'icon-lamp' : '&#xe00e;',
			'icon-shield' : '&#xe00f;',
			'icon-tie' : '&#x2040;',
			'icon-intersection' : '&#x2229;',
			'icon-desklamp' : '&#xf412;',
			'icon-avengers' : '&#xf342;',
			'icon-captainamerica' : '&#xf341;',
			'icon-walle' : '&#xf3bc;',
			'icon-monstersinc' : '&#xf3bd;',
			'icon-shopping' : '&#xf010;',
			'icon-wheelchair' : '&#xf3fe;',
			'icon-home' : '&#xf0b4;',
			'icon-volumefull' : '&#xf0e2;',
			'icon-volumehalf' : '&#xf0e3;',
			'icon-volumemute2' : '&#xf0e5;',
			'icon-cogs' : '&#xf12b;',
			'icon-cog' : '&#xf189;',
			'icon-export' : '&#xf16b;',
			'icon-podcast' : '&#xf1a2;',
			'icon-share' : '&#xf29d;',
			'icon-sharethis' : '&#xe068;',
			'icon-pocket' : '&#xe032;',
			'icon-envelope' : '&#xe014;',
			'icon-mail' : '&#xe003;',
			'icon-mail-2' : '&#xe015;',
			'icon-feed' : '&#xe024;',
			'icon-feed-2' : '&#xe025;',
			'icon-feed-3' : '&#xe066;',
			'icon-facebook' : '&#xe020;',
			'icon-facebook-2' : '&#xe021;',
			'icon-facebook-3' : '&#xe061;',
			'icon-twitter' : '&#xe022;',
			'icon-twitter-2' : '&#xe023;',
			'icon-twitter-3' : '&#xe062;',
			'icon-pinterest' : '&#xe028;',
			'icon-pinterest-2' : '&#xe035;',
			'icon-pinterest-3' : '&#xe02a;',
			'icon-stumbleupon' : '&#xe02b;',
			'icon-stumbleupon-2' : '&#xe033;',
			'icon-stumbleupon-3' : '&#xe02c;',
			'icon-linkedin' : '&#xe030;',
			'icon-linkedin-2' : '&#xe06a;',
			'icon-linkedin-3' : '&#xe06b;',
			'icon-flickr' : '&#xe05c;',
			'icon-flickr-2' : '&#xe05d;',
			'icon-flickr-3' : '&#xe063;',
			'icon-dribbble' : '&#xe05e;',
			'icon-dribbble-2' : '&#xe05f;',
			'icon-dribbble-3' : '&#xe064;',
			'icon-instagram' : '&#xe031;',
			'icon-instagram-2' : '&#xf14a;',
			'icon-github' : '&#xe034;',
			'icon-github-2' : '&#xe036;',
			'icon-github-3' : '&#xe039;',
			'icon-skype' : '&#xe03b;',
			'icon-skype-2' : '&#xe03a;',
			'icon-reddit' : '&#xe03c;',
			'icon-delicious' : '&#xe048;',
			'icon-stackoverflow' : '&#xe04c;',
			'icon-youtube' : '&#xe050;',
			'icon-vimeo' : '&#xe052;',
			'icon-vimeo-2' : '&#xe054;',
			'icon-soundcloud' : '&#xe055;',
			'icon-deviantart' : '&#xe05a;',
			'icon-picassa' : '&#xe060;',
			'icon-rdio' : '&#xe065;',
			'icon-spotify' : '&#xe067;',
			'icon-behance' : '&#xe069;',
			'icon-lastfm' : '&#xe06c;',
			'icon-wordpress' : '&#xe06d;',
			'icon-google' : '&#xe002;',
			'icon-foursquare' : '&#xe06e;',
			'icon-googleplus' : '&#xe00d;',
			'icon-googleplus-2' : '&#xe06f;',
			'icon-googleplus-3' : '&#xf086;',
			'icon-paypal' : '&#xf0e6;',
			'icon-apple' : '&#xe00b;',
			'icon-android' : '&#xf085;',
			'icon-windows8' : '&#xf03a;',
			'icon-bluetooth' : '&#xe05b;',
			'icon-earth' : '&#xf482;',
			'icon-paw' : '&#xe026;',
			'icon-menu' : '&#xe01f;',
			'icon-list' : '&#xe027;'
		},
		els = document.getElementsByTagName('*'),
		i, attr, html, c, el;
	for (i = 0; i < els.length; i += 1) {
		el = els[i];
		attr = el.getAttribute('data-icon');
		if (attr) {
			addIcon(el, attr);
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
};